<h3><strong>SCHULMANIN TAIDELIIKE OY</strong></h3>

<h3><strong>Kasarmikatu 2, 00140 Helsinki</strong></h3>

<p><strong>Avoinna: ma-pe 12-17, la 11-14.</strong><br />
<br />
<strong>Puh: 040-5247773, 050-3501493, 09-2600613</strong> <strong>(international: 00358 40 5247773)</strong><br />
<br />
<strong>Kotisivut: WWW.SCHULMANANTIQUES.FI</strong></p>

<h3><strong>e-mail: <a href="mailto:j.schulman@schulmanantiques.fi">j.schulman@schulmanantiques.fi</a></strong></h3>

<h3><a href="http://www.facebook.com/schulmanantiques"><strong>www.facebook.com/schulmanantiques</strong></a></h3>
