<h3><strong>SCHULMANS KONSTHANDEL AB</strong></h3>

<h3><strong>KASERNGATAN 2, 00140 HELSINGFORS</strong></h3>
<br />
<strong>&Ouml;PPET</strong><strong>: M&Aring; - FRE 12-17, L&Ouml;: 11-14</strong>

<p>&nbsp;</p>

<h3><strong>TEL: 040-5247773, 050-3501493, 09-2600613 (international: 00358 40 5247773)</strong></h3>

<p><br />
<strong>HEMSIDA: WWW.SCHULMANANTIQUES.FI</strong></p>

<h3><strong>e-mail: <a href="mailto:j.schulman@schulmanantiques.fi">j.schulman@schulmanantiques.fi</a></strong></h3>

<h3><a href="http://www.facebook.com/schulmanantiques"><strong>www.facebook.com/schulmanantiques</strong></a><br />
&nbsp;</h3>
