<p>Uudistettu Nexus 7 nyt my&ouml;s Suomesta! Huippuluokan Android-tabletti nyt entist&auml;kin parempana! Uudistuksista mainittakoon mm. 1920x1200 resoluution n&auml;ytt&ouml;, 5 MP takakamera, Qualcomm Snapdragon S4Pro -suoritin ja 2 GB keskusmuisti.</p>

<p><strong>T&auml;rkeimm&auml;t ominaisuudet:</strong></p>

<ul>
	<li>Prosessori: Qualcomm Snapdragon S4Pro Quad-core 1.5 GHz</li>
	<li>K&auml;ytt&ouml;j&auml;rjestelm&auml;: Google Android OS v4.3</li>
	<li>N&auml;ytt&ouml;: 7&quot; LED LCD kapasitiivinen IPS kosketusn&auml;ytt&ouml;, WUXGA (1920x1200) resoluutio</li>
	<li>Kamera: edess&auml; 1.2 mpxl, takana 5.0 mpxl</li>
	<li>Muisti: 32 GB sis&auml;inen FLASH-muisti</li>
	<li>Yhteydet: WLAN (b/g/n), Bluetooth v4.0, NFC</li>
	<li>Muuta: GPS, Android Market, Gyroskooppi, elektroninen kompassi, kiihtyvyysanturi, valoisuusanturi, Google-sovellukset</li>
	<li>Akku: Li-Pol</li>
	<li>Toiminta-ajat: 10 h</li>
	<li>Mitat: koko 114 x 200 x 8.65 mm, paino 290 g</li>
</ul>

<p>Myyntipakkauksen sis&auml;lt&ouml;:</p>

<ul>
	<li>Asus Nexus 7 2013 Android 4.3 -tablet</li>
	<li>Verkkovirtalaturi</li>
	<li>Datakaapeli</li>
	<li>K&auml;ytt&ouml;opas</li>
</ul>
