<p>Samsung Galaxy Tab 3 10.1. T&auml;ydellinen viihdelaite koko perheelle. Ter&auml;v&auml;ll&auml; kuvalla, loistavalla v&auml;rintoistolla ja ylivertaisella Sound Alive -tekniikalla h&ouml;ystetty &auml;&auml;ni tekee uudesta Tabista t&auml;ydellisen vaikkapa elokuvien tai muun viihdesis&auml;ll&ouml;n katsomiseen. Laitteessa on rungossa fyysiset painikkeet, jotta kuva-ala saadaan kokonaan viihteen k&auml;ytt&ouml;&ouml;n. Lis&auml;ksi Tab 3.0 toimii uusien Smart TV:eiden yleiskaukos&auml;&auml;timen&auml;. Google Play -kaupasta ladattava Peel Samsung Remote tekee Tab 3:sta kaukos&auml;&auml;timen ja television ohjelmaoppaan. Se toimii k&auml;tev&auml;n&auml; muistuttajana, ettei k&auml;ytt&auml;j&auml; unohda omia suosikkiohjelmiaan.</p>

<p><strong>T&auml;rkeimm&auml;t ominaisuudet:</strong></p>

<ul>
	<li>N&auml;ytt&ouml;: 10,1&quot; WXGA 1280 x 800 TFT-n&auml;ytt&ouml;</li>
	<li>Suoritin: 1.6 GHz tuplaydinsuoritin</li>
	<li>Muisti: 1 GB RAM-muistia, 16 GB sis&auml;&auml;nrakennettu tallennustila, MicroSD-korttipaikka (maks. 64 GB)</li>
	<li>K&auml;ytt&ouml;j&auml;rjestelm&auml;: Android 4.2 Jelly Bean</li>
	<li>Yhteydet: Wi-Fi a/b/g/n 2,4 + 5 Ghz langaton yhteys, Wi-Fi Direct -tuki, Bluetooth 4.0, DLNA</li>
	<li>Liit&auml;nn&auml;t: USB 2.0, 3,5 mm stereokuulokeliit&auml;nt&auml;, Micro USB (5 V, 2 A), MHL 1.2</li>
	<li>Kamera: 1,3 megapikseli&auml; (edess&auml;), 3 megapikseli&auml; (takana)</li>
	<li>Paikannus: GPS + GLONASS</li>
	<li>Akku: 6800 mAh akku, jopa 9 tunnin videon toistoaika</li>
	<li>Anturit: kiihtyvyysanturi, geomagneettinen anturi, valoanturi</li>
	<li>Mitat (L x S x K): 176,1 x 243,1 x 7,95 mm</li>
	<li>Paino: 510 g</li>
</ul>
