<h3><br />
<br />
<strong>Tervetuloa Schulmanin Taideliikkeen kotisivulle!<br />
<br />
Olemme toimineet Helsingiss&auml; yli 17 vuotta ja osallistuneet 1997-2014 v&auml;lisen&auml; aikana yli 50 messutapahtumiin. Nykyisell&auml; osoitteella olemme toimineet vuodesta 2003. Meilt&auml; l&ouml;yd&auml;t huolella valikoitua taidetta ja antiikkia eri hintaluokissa. Hurmaavia esineit&auml; yksil&ouml;lliseen makuun; maalauksia, veistoksia, huonekaluja, peilej&auml;, kattokruunuja, lasia ja posliinia ym p&auml;&auml;asiassa ajalta 1750-1950. Klassillista ja modernia. Alkuper&auml;iskunnossa olevaa ja restauroitua. Ker&auml;ilij&auml;lle ja sisustajalle. Uusia esineit&auml; melkein joka p&auml;iv&auml;! Yrit&auml;mme pit&auml;&auml; kotisivut ajan tasalla, mutta parhaiten n&auml;kee tietysti aina paikan p&auml;&auml;ll&auml;.</strong></h3>
<strong>Yksil&ouml;llinen sisustaminen alkaa t&auml;&auml;lt&auml;!</strong>

<h2>Kasarmikatu 2, 00140 Helsinki (Vuorimiehenkadun kulma)<br />
<strong>Liike on auki ark. 12-17 lauant. 11-14</strong></h2>
