<h2>&nbsp;</h2>

<h3><strong>Schulmans Konsthandel &auml;r ett f&ouml;retag som verkat i Helsingfors i 17&nbsp;&aring;r. P&aring; v&aring;r nuvarande adress har vi verkat<br />
sedan 2003,&nbsp;och har sedan starten deltagit i &ouml;ver 50 antikm&auml;ssor i huvudstadsregionen.&nbsp;Vi</strong><strong>&nbsp;&auml;r specialiserade p&aring; gammal<br />
konst och &auml;kta&nbsp;antikviteter med h&ouml;g charmfaktor.</strong> <strong>Kontinuerligt f&ouml;revisas</strong> <strong>omkring 100 m&aring;lningar fr&aring;n 1700 och 1800-talenn, fr&auml;mst&nbsp;i prisklassen 300 - 3000 euro.</strong> <strong>Vi saluf&ouml;r huvudsakligen skandinavisk och europeisk bildkonst d&auml;r pris och<br />
konstn&auml;rlig&nbsp;kvalitet</strong> <strong>f&ouml;rdelaktigt sammanfaller. &Auml;ven gammal och modern finsk konst f&ouml;revisas. Bland antikviteterna satsar vi&nbsp;p&aring; alster fr&auml;mst fr&aring;n 1750-1850; barock, rokoko, gustavianskt och empire. Sittm&ouml;bler, bord, byr&aring;er, takkronor, speglar ect.&nbsp;&Auml;ven glas, porslin och samlarf&ouml;rem&aring;l.<br />
V&auml;lkommen och se hurudana saker du kan f&aring; f&ouml;r dina pengar! Personlig inredning b&ouml;rjar hos oss!</strong></h3>

<h2>Kaserngatan 2, 00140 Helsingfors (h&ouml;rnet Bergmansgatan)</h2>

<p><strong>Aff&auml;ren &auml;r &ouml;ppen vard 12-17 l&ouml;rdagar 11-14</strong></p>
