<strong>Nexus 4</strong>
<p>LG Nexus 4 on LG:n ja Googlen yhteisty&ouml;ss&auml; valmistama Android-puhelin, jonka tehokas neliydinprosessori, upea True HD IPS Plus -n&auml;ytt&ouml; ja takakuoren uniikki v&auml;ritys erottavat puhelimen massasta.</p>

<p>Nexus 4:ss&auml; on suorituskykyinen 8 megapikselin kamera, jonka Photo Sphere -toiminnon avulla voit ikuistaa maailman ymp&auml;rill&auml;si uskomattoman upeiksi kuviksi. Matkapuhelimen suuressa 4,7 tuuman True HD IPS Plus -n&auml;yt&ouml;ss&auml; kuvat her&auml;&auml;v&auml;t eloon todella ter&auml;vin&auml; ja luonnollisina. N&auml;yt&ouml;n tarkkuus on 1280 x 768 kuvapistett&auml; ja sen pikselitiheys on 320 ppi.</p>

<p>Reunoista pehme&auml;sti py&ouml;ristetyn lasin ansiosta sormet liukuvat n&auml;yt&ouml;ll&auml; tasaisen sulavasti ja vallankumouksellinen Zerogap Touch n&auml;ytt&ouml;tekniikka tuo n&auml;yt&ouml;n kuvan niin l&auml;helle, ett&auml; k&auml;ytt&auml;j&auml;st&auml; tuntuu, kuin h&auml;n koskettaisi lasin sijasta itse kuvaa. N&auml;yt&ouml;n suojana on hankausta kest&auml;v&auml; Corning&reg; Gorilla&reg; Glass 2 -lasi.</p>

<p>T&auml;rkeimm&auml;t ominaisuudet:</p>

<ul>
	<li>GSM-taajuudet: 850/900/1800/1900MHz</li>
	<li>3G-taajuudet: 850/900/1700/1900/2100MHz</li>
	<li>Prosessori:&nbsp;Quad-core 1.5 GHz Krait,&nbsp;Qualcomm APQ8064 Snapdragon,&nbsp;Adreno 320</li>
	<li>K&auml;ytt&ouml;j&auml;rjestelm&auml;: Google Android OS v4.2 (Jelly Bean)</li>
	<li>N&auml;ytt&ouml;: 4.7&quot; True HD IPS Plus kapasitiivinen kosketusn&auml;ytt&ouml;, 768 x 1280 resoluutio, 16M v&auml;ri&auml;</li>
	<li>Kamera: 8.0 mpxl (3264x2448), automaattitarkennus, LED-salama, Geo-Tagging, kasvontunnistus, video (1080p@30fps), videopuhelukamera</li>
	<li>Soitto&auml;&auml;net: MP3, WAV</li>
	<li>Muisti: 8 GB, 2 GB RAM</li>
	<li>Yhteydet: GPRS, EDGE, 3G, HSDPA (21 Mbps), HSUPA (5.76 Mbps), WLAN (a/b/g/n + DLNA-tuki), Bluetooth v4.0 (A2DP-Bluetooth-stereo -tuki), microUSB v2.0</li>
	<li>Muuta: Sis&auml;&auml;nrakennettu GPS-vastaanotin (A-GPS -tuki), GLONASS, digitaalinen kompassi, aktiivinen melunvaimennus omalla mikrofonillaan, Google Search, Google Maps, Gmail, YouTube, Google Calendar, Google Talk, Picasa integrointi, NFC-tuki, TV-ulostulo (MHL-adapterilla), langaton lataus (Qi-tekniikalla)</li>
	<li>Akku: Li-Ion (2100 mAh)</li>
	<li>Toiminta-ajat:&nbsp; puheaika 15 h (3G) /&nbsp; valmiusaika 390h (3G)</li>
	<li>Mitat: koko 133.9 x 68.7 x 9.1 mm, paino 139 g</li>
</ul>

<p><strong>Huom! Puhelin k&auml;ytt&auml;&auml; microSIM-korttia!</strong></p>
